module.exports = {
  PARTDCEXCHANGECODAL_REDIS_SERVER: process.env.PARTDCEXCHANGECODAL_REDIS_SERVER,
  PARTDCEXCHANGECODAL_REDIS_INDEX: process.env.PARTDCEXCHANGECODAL_REDIS_INDEX,
  PARTDCEXCHANGECODAL_MONGO_SERVER: process.env.PARTDCEXCHANGECODAL_MONGO_SERVER,
  PARTDCEXCHANGECODAL_REDIS_PASSWORD : process.env.PARTDCEXCHANGECODAL_REDIS_PASSWORD,
  PARTDCEXCHANGECODAL_MONGO_PORT: process.env.PARTDCEXCHANGECODAL_MONGO_PORT,
  PARTDCEXCHANGECODAL_MONGO_PASSWORD:process.env.PARTDCEXCHANGECODAL_MONGO_PASSWORD,
  PARTDCEXCHANGECODAL_MONGO_USERNAME:process.env.PARTDCEXCHANGECODAL_MONGO_USERNAME,
  PARTDCEXCHANGECODAL_MONGO_AUTH:process.env.PARTDCEXCHANGECODAL_MONGO_AUTH,
  PARTDCEXCHANGECODAL_MONGO_DATABASENAME : process.env.PARTDCEXCHANGECODAL_MONGO_DATABASENAME,
  PARTDCEXCHANGECODAL_DLS_HOST: process.env.PARTDCEXCHANGECODAL_DLS_HOST,
  PARTDCEXCHANGECODAL_DLS_PATH: process.env.PARTDCEXCHANGECODAL_DLS_PATH,
  PARTDCEXCHANGECODAL_URL_STOCKLIST : process.env.PARTDCEXCHANGECODAL_URL_STOCKLIST,
  PARTDCEXCHANGECODAL_URL_FUNDLIST : process.env.PARTDCEXCHANGECODAL_URL_FUNDLIST
};
